import { Blog } from "@/components/Blog";

export default function Ribonanza() {
    return <Blog title="Stanford Ribonanza RNA Folding" github="https://github.com/chrehall68/sjsu-ml-f23-ribonanza" brief="Learning to fold RNA sequences with PyTorch and Transformers">

        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fames ac turpis egestas maecenas pharetra convallis. Tristique sollicitudin nibh sit amet commodo nulla. Commodo quis imperdiet massa tincidunt nunc pulvinar. Et netus et malesuada fames. Tristique senectus et netus et malesuada fames ac turpis. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Pulvinar pellentesque habitant morbi tristique senectus et. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Purus in mollis nunc sed id semper risus in hendrerit. Sed blandit libero volutpat sed. Nibh venenatis cras sed felis eget velit aliquet. Volutpat sed cras ornare arcu dui vivamus arcu. Quam adipiscing vitae proin sagittis. Duis ut diam quam nulla porttitor massa id neque. Dui vivamus arcu felis bibendum ut tristique et egestas. Eu turpis egestas pretium aenean pharetra. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum.

        Et netus et malesuada fames ac turpis egestas integer eget. Nec ullamcorper sit amet risus nullam eget felis eget. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Urna et pharetra pharetra massa massa ultricies mi. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tortor at auctor urna nunc id cursus metus aliquam. Risus commodo viverra maecenas accumsan lacus vel facilisis. Dignissim sodales ut eu sem integer vitae justo. Sapien eget mi proin sed libero enim sed. Ultrices sagittis orci a scelerisque. Imperdiet proin fermentum leo vel orci porta. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Interdum velit euismod in pellentesque. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Id interdum velit laoreet id. Amet commodo nulla facilisi nullam vehicula ipsum a.

        Quam quisque id diam vel quam elementum pulvinar. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Quis vel eros donec ac odio tempor orci. Nisl nunc mi ipsum faucibus vitae aliquet. Massa sapien faucibus et molestie ac. Eget nunc lobortis mattis aliquam faucibus purus in massa. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Nunc sed augue lacus viverra vitae congue eu consequat. Tempor orci eu lobortis elementum nibh. Congue eu consequat ac felis donec et odio. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Euismod in pellentesque massa placerat duis ultricies lacus sed. Nulla facilisi cras fermentum odio eu. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Vel pharetra vel turpis nunc eget lorem. Scelerisque felis imperdiet proin fermentum leo vel orci porta non.

        Diam sollicitudin tempor id eu nisl nunc mi. Eu sem integer vitae justo eget magna fermentum. Nunc id cursus metus aliquam eleifend mi in. Massa id neque aliquam vestibulum morbi blandit cursus. Consequat semper viverra nam libero justo. Bibendum at varius vel pharetra vel. Venenatis a condimentum vitae sapien pellentesque habitant. Arcu vitae elementum curabitur vitae. Ut tristique et egestas quis ipsum. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Mattis molestie a iaculis at. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh.

        Pharetra massa massa ultricies mi quis hendrerit. Porta lorem mollis aliquam ut porttitor. Duis ut diam quam nulla porttitor. Semper risus in hendrerit gravida rutrum quisque non. Faucibus scelerisque eleifend donec pretium vulputate sapien. Amet cursus sit amet dictum sit amet justo. Purus non enim praesent elementum. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Lacus viverra vitae congue eu consequat ac felis donec. Orci porta non pulvinar neque laoreet suspendisse interdum. Pretium fusce id velit ut tortor pretium. Ornare lectus sit amet est placerat in egestas erat. Ultrices eros in cursus turpis massa. Neque sodales ut etiam sit amet nisl purus in. Neque aliquam vestibulum morbi blandit cursus. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Suspendisse interdum consectetur libero id. Netus et malesuada fames ac turpis egestas integer eget aliquet. Amet massa vitae tortor condimentum lacinia. Iaculis at erat pellentesque adipiscing commodo.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fames ac turpis egestas maecenas pharetra convallis. Tristique sollicitudin nibh sit amet commodo nulla. Commodo quis imperdiet massa tincidunt nunc pulvinar. Et netus et malesuada fames. Tristique senectus et netus et malesuada fames ac turpis. Adipiscing bibendum est ultricies integer quis auctor elit sed vulputate. Pulvinar pellentesque habitant morbi tristique senectus et. Ultricies tristique nulla aliquet enim tortor at auctor urna nunc. Purus in mollis nunc sed id semper risus in hendrerit. Sed blandit libero volutpat sed. Nibh venenatis cras sed felis eget velit aliquet. Volutpat sed cras ornare arcu dui vivamus arcu. Quam adipiscing vitae proin sagittis. Duis ut diam quam nulla porttitor massa id neque. Dui vivamus arcu felis bibendum ut tristique et egestas. Eu turpis egestas pretium aenean pharetra. Fermentum et sollicitudin ac orci phasellus egestas tellus rutrum.

        Et netus et malesuada fames ac turpis egestas integer eget. Nec ullamcorper sit amet risus nullam eget felis eget. Sem viverra aliquet eget sit amet tellus cras adipiscing enim. Urna et pharetra pharetra massa massa ultricies mi. Scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Lorem mollis aliquam ut porttitor leo a diam sollicitudin. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Tortor at auctor urna nunc id cursus metus aliquam. Risus commodo viverra maecenas accumsan lacus vel facilisis. Dignissim sodales ut eu sem integer vitae justo. Sapien eget mi proin sed libero enim sed. Ultrices sagittis orci a scelerisque. Imperdiet proin fermentum leo vel orci porta. Leo integer malesuada nunc vel risus commodo viverra maecenas accumsan. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Interdum velit euismod in pellentesque. Nascetur ridiculus mus mauris vitae ultricies leo integer malesuada. Id interdum velit laoreet id. Amet commodo nulla facilisi nullam vehicula ipsum a.

        Quam quisque id diam vel quam elementum pulvinar. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Quis vel eros donec ac odio tempor orci. Nisl nunc mi ipsum faucibus vitae aliquet. Massa sapien faucibus et molestie ac. Eget nunc lobortis mattis aliquam faucibus purus in massa. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Nunc sed augue lacus viverra vitae congue eu consequat. Tempor orci eu lobortis elementum nibh. Congue eu consequat ac felis donec et odio. Pharetra vel turpis nunc eget lorem dolor sed viverra ipsum. Id velit ut tortor pretium viverra suspendisse potenti nullam ac. Euismod in pellentesque massa placerat duis ultricies lacus sed. Nulla facilisi cras fermentum odio eu. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Vel pharetra vel turpis nunc eget lorem. Scelerisque felis imperdiet proin fermentum leo vel orci porta non.

        Diam sollicitudin tempor id eu nisl nunc mi. Eu sem integer vitae justo eget magna fermentum. Nunc id cursus metus aliquam eleifend mi in. Massa id neque aliquam vestibulum morbi blandit cursus. Consequat semper viverra nam libero justo. Bibendum at varius vel pharetra vel. Venenatis a condimentum vitae sapien pellentesque habitant. Arcu vitae elementum curabitur vitae. Ut tristique et egestas quis ipsum. Scelerisque eu ultrices vitae auctor eu augue ut lectus. Mattis molestie a iaculis at. In fermentum posuere urna nec tincidunt praesent semper feugiat nibh.

        Pharetra massa massa ultricies mi quis hendrerit. Porta lorem mollis aliquam ut porttitor. Duis ut diam quam nulla porttitor. Semper risus in hendrerit gravida rutrum quisque non. Faucibus scelerisque eleifend donec pretium vulputate sapien. Amet cursus sit amet dictum sit amet justo. Purus non enim praesent elementum. Mauris ultrices eros in cursus turpis massa tincidunt dui ut. Lacus viverra vitae congue eu consequat ac felis donec. Orci porta non pulvinar neque laoreet suspendisse interdum. Pretium fusce id velit ut tortor pretium. Ornare lectus sit amet est placerat in egestas erat. Ultrices eros in cursus turpis massa. Neque sodales ut etiam sit amet nisl purus in. Neque aliquam vestibulum morbi blandit cursus. Vivamus arcu felis bibendum ut tristique et egestas quis ipsum. Suspendisse interdum consectetur libero id. Netus et malesuada fames ac turpis egestas integer eget aliquet. Amet massa vitae tortor condimentum lacinia. Iaculis at erat pellentesque adipiscing commodo.

    </Blog>
}